[package]
name = "chorduroy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
coremidi = "0.7.0"
cpal = "0.15.1"
itertools = "0.10.5"
rand = "0.8.5"
textplots = "0.8.0"
